spring:
  jpa:
    properties:
      hibernate:
        generate_statistics: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/demoproject
    username: postgres
    password: password!456
    driver-class-name: org.postgresql.Driver

